name: Deploy cancel-order to EC2 (qa)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cancel-order:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cancel-order:latest

    - name: SSH into EC2 and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Ensure Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "🔧 Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          # Stop and remove old container if it exists
          echo "🛑 Stopping old container (if any)..."
          sudo docker stop cancel-order || true
          sudo docker rm cancel-order || true

          # Pull latest image from Docker Hub
          echo "📥 Pulling latest image..."
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cancel-order:latest

          # Run new container
          echo "🚀 Running container..."
          sudo docker run -d \
            --name cancel-order \
            --restart=always \
            -p 4002:4002 \
            ${{ secrets.DOCKER_USERNAME }}/cancel-order:latest